using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Session3InheritanceAccesModifiersAutoPropStatic.Exercise5
{
    class Book
    {
        //private string bookName;
        private string bookAuthor;
        private int bookPages;
        private bool bookAvailable;

        public Book(string bookName, string bookAuthor, int bookPages, bool bookAvailable)
        {
            this.BookName = bookName;//Autogenerated attributes(excludes line 11)
            this.bookAuthor = bookAuthor;
            this.bookPages = bookPages;
            this.bookAvailable = bookAvailable;
        }
        public string BookName { get; private set; }//modify the setter only inside the class
        public string BookAuthor { get; set; }//string
        public int BookPages { get; set; }//int

        //explicit reference
        public bool BookAvailable
        {
            get { return bookAvailable; }
            set { bookAvailable = value; }
        }

        /*   //other member is generated (parameter sniffing)
           public void setBookAvailable(bool bookAvailable)
           {
               this.bookAvailable = bookAvailable;
           }
           public bool getBookAvailable()
           {
               return bookAvailable;
           }*/
        //I also used ToString to display properly and to use override
        public override string ToString()
        {
            return "Book name: " + BookName + ", author: " + bookAuthor + " ,pages: " + bookPages + " Book available? " + bookAvailable;
        }
    }
}
